In [28]:
import numpy as np

Create Array

In [29]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

print("Original Array:")
print(array)

Original Array:
[[ 1 -2  3]
 [-4  5 -6]]


Q2(i) — Element-wise Absolute Value

In [30]:
print("Element-wise Absolute Value:")

print(np.abs(array))

Element-wise Absolute Value:
[[1 2 3]
 [4 5 6]]


Q2(ii) — Percentiles

You need:

25th percentile
50th percentile
75th percentile

for:

Flattened array
Each column
Each row

In [31]:
print("Flattened Array Percentiles:")

print(np.percentile(array, [25, 50, 75]))

Flattened Array Percentiles:
[-3.5 -0.5  2.5]


 Column-wise Percentiles

In [32]:
print("Column-wise Percentiles:")

print(np.percentile(array, [25, 50, 75], axis=0))

Column-wise Percentiles:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


Row-wise Percentiles

In [33]:
print("Row-wise Percentiles:")

print(np.percentile(array, [25, 50, 75], axis=1))

Row-wise Percentiles:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


Q2(iii) — Mean, Median and Standard Deviation

In [34]:
print("Flattened Array Statistics:")

print("Mean =", np.mean(array))
print("Median =", np.median(array))
print("Standard Deviation =", np.std(array))

Flattened Array Statistics:
Mean = -0.5
Median = -0.5
Standard Deviation = 3.8622100754188224


Column-wise Statistics

In [35]:
print("Column-wise Statistics:")

print("Mean:")
print(np.mean(array, axis=0))

print("Median:")
print(np.median(array, axis=0))

print("Standard Deviation:")
print(np.std(array, axis=0))

Column-wise Statistics:
Mean:
[-1.5  1.5 -1.5]
Median:
[-1.5  1.5 -1.5]
Standard Deviation:
[2.5 3.5 4.5]


Row-wise Statistics

In [36]:
print("Row-wise Statistics:")

print("Mean:")
print(np.mean(array, axis=1))

print("Median:")
print(np.median(array, axis=1))

print("Standard Deviation:")
print(np.std(array, axis=1))

Row-wise Statistics:
Mean:
[ 0.66666667 -1.66666667]
Median:
[ 1. -4.]
Standard Deviation:
[2.05480467 4.78423336]


# Q3: NumPy Mathematical Functions

In [37]:
import numpy as np

In [38]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Original Array:")
print(a)

Original Array:
[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]


In [39]:
print("Floor Values:")

print(np.floor(a))

Floor Values:
[-2. -2. -1.  0.  1.  1.  3.]


In [40]:
print("Ceiling Values:")

print(np.ceil(a))

Ceiling Values:
[-1. -1. -0.  1.  2.  2.  3.]


In [41]:
print("Truncated Values:")

print(np.trunc(a))

Truncated Values:
[-1. -1. -0.  0.  1.  1.  3.]


In [42]:
print("Rounded Values:")

print(np.round(a))

Rounded Values:
[-2. -2. -0.  0.  2.  2.  3.]


In [43]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Original Array:")
print(a)

print("\nFloor Values:")
print(np.floor(a))

print("\nCeiling Values:")
print(np.ceil(a))

print("\nTruncated Values:")
print(np.trunc(a))

print("\nRounded Values:")
print(np.round(a))

Original Array:
[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor Values:
[-2. -2. -1.  0.  1.  1.  3.]

Ceiling Values:
[-1. -1. -0.  1.  2.  2.  3.]

Truncated Values:
[-1. -1. -0.  0.  1.  1.  3.]

Rounded Values:
[-2. -2. -0.  0.  2.  2.  3.]


In [44]:
# Q4: Swap Two Elements in a List Using Temporary Variable

In [45]:
my_list = [10, 20, 30, 40]

print("Original List:")
print(my_list)

Original List:
[10, 20, 30, 40]


In [46]:
pos1 = 1
pos2 = 3

In [47]:
temp = my_list[pos1]

my_list[pos1] = my_list[pos2]

my_list[pos2] = temp

In [48]:
temp = my_list[pos1]

In [49]:
my_list[pos1] = my_list[pos2]

In [50]:
my_list[pos2] = temp

In [51]:
print("List After Swapping:")
print(my_list)

List After Swapping:
[10, 20, 30, 40]


In [52]:
# Create list
my_list = [10, 20, 30, 40]

print("Original List:")
print(my_list)

# Positions to swap
pos1 = 1
pos2 = 3

# Swapping using temporary variable
temp = my_list[pos1]

my_list[pos1] = my_list[pos2]

my_list[pos2] = temp

# Display updated list
print("List After Swapping:")
print(my_list)

Original List:
[10, 20, 30, 40]
List After Swapping:
[10, 40, 30, 20]


# Q5: Swap Two Elements in a Set by Converting it into a List

In [53]:
my_set = {1, 2, 3, 4}

print("Original Set:")
print(my_set)

Original Set:
{1, 2, 3, 4}


In [54]:
temp_list = list(my_set)

print("Converted List:")
print(temp_list)

Converted List:
[1, 2, 3, 4]


In [55]:
temp = temp_list[0]

temp_list[0] = temp_list[1]

temp_list[1] = temp

In [56]:
my_set = set(temp_list)

print("Set After Swapping:")
print(my_set)

Set After Swapping:
{1, 2, 3, 4}


# Create set
my_set = {1, 2, 3, 4}

print("Original Set:")
print(my_set)

# Convert set into list
temp_list = list(my_set)

print("\nConverted List:")
print(temp_list)

# Swap first two elements
temp = temp_list[0]

temp_list[0] = temp_list[1]

temp_list[1] = temp

# Convert back to set
my_set = set(temp_list)

print("\nSet After Swapping:")
print(my_set)