# Part II: Data Manipulation and Analysis (Pandas)

This section performs statistical analysis and data manipulation using Pandas.

In [35]:
import numpy as np
import pandas as pd

## Step 1: Display First 5 Rows and Summary Statistics

The first 5 rows and statistical summary of the dataset are displayed for analysis.

In [36]:
print(df.head())

     Electronics   Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan      4024.89  2733.9400            4390    4796  34813.500000          NaN
Feb      3437.64  3025.8300            1590    1711  22378.804984   -35.718026
Mar      2531.25  3083.6300            4711    4697  32692.494409    46.086864
Apr      1985.31  2491.1800            4771    2994  26547.028492   -18.797788
May      3812.67  2204.3475            1095    1889  20534.265340   -22.649477


In [37]:
print(df.describe())

       Electronics     Clothing  Home & Kitchen       Sports   Total Sales  \
count    12.000000    12.000000       12.000000    12.000000     12.000000   
mean   2871.180000  2517.491042     3309.500000  3224.250000  26250.056084   
std     736.630628   742.213724     1467.358883  1264.542255   4503.744515   
min    1961.010000  1103.980000     1095.000000  1241.000000  20534.265340   
25%    2314.777500  2106.810000     1798.500000  2237.000000  23153.262021   
50%    2663.685000  2765.730000     3551.000000  3307.000000  25779.824273   
75%    3464.370000  3018.243750     4726.000000  4327.250000  28106.980318   
max    4024.890000  3589.380000     4972.000000  4796.000000  34813.500000   

       Growth Rate  
count    11.000000  
mean      1.831824  
std      26.493173  
min     -35.718026  
25%     -20.723633  
50%       4.388239  
75%      18.703105  
max      46.086864  


## Step 2: Calculate Total Sales

Total sales are calculated:
- Category-wise
- Month-wise

In [38]:
category_total = df.sum()

print(category_total)

Electronics        34454.160000
Clothing           30209.892500
Home & Kitchen     39714.000000
Sports             38691.000000
Total Sales       315000.673013
Growth Rate           20.150060
dtype: float64


In [39]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    50758.330000
Feb    32107.556957
Mar    47761.461273
Apr    38769.720704
May    29512.633362
Jun    39540.690952
Jul    34372.889467
Aug    39790.349781
Sep    30186.801327
Oct    34737.613932
Nov    36729.108293
Dec    43822.719525
dtype: float64


## Step 3: Average Sales Growth

Percentage growth between consecutive months is calculated for each category.

In [40]:
growth = df.pct_change()

print(growth)

     Electronics  Clothing  Home & Kitchen    Sports  Total Sales  Growth Rate
Jan          NaN       NaN             NaN       NaN          NaN          NaN
Feb    -0.145905  0.106765       -0.637813 -0.643244    -0.357180          NaN
Mar    -0.263666  0.019102        1.962893  1.745178     0.460869    -2.290297
Apr    -0.215680 -0.192127        0.012736 -0.362572    -0.187978    -1.407877
May     0.920441 -0.115139       -0.770488 -0.369071    -0.226495     0.204901
Jun    -0.102401  0.269092        0.660274  1.225516     0.327836    -2.447433
Jul    -0.426982 -0.491477        1.734873 -0.376784    -0.141374    -1.431234
Aug     0.194961  1.523108       -0.190467 -0.101908     0.173032    -2.223930
Sep     0.512617 -0.494565       -0.321491 -0.472588    -0.239686    -2.385210
Oct    -0.361517  0.613700       -0.362871  2.087027     0.147564    -1.615656
Nov     0.235505 -0.622902        0.768391  0.235970     0.043882    -0.702621
Dec    -0.165991  1.731675        0.558011 -0.235480

In [41]:
avg_growth = growth.mean()

print(avg_growth)

Electronics       0.016489
Clothing          0.213385
Home & Kitchen    0.310368
Sports            0.248367
Total Sales       0.018318
Growth Rate      -1.071825
dtype: float64


## Step 4: Add New Columns

Two new columns are added:
- Total Sales
- Growth Rate

In [42]:
df['Total Sales'] = df.sum(axis=1)

print(df)

     Electronics   Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan      4024.89  2733.9400            4390    4796  50758.330000          NaN
Feb      3437.64  3025.8300            1590    1711  32107.556957   -35.718026
Mar      2531.25  3083.6300            4711    4697  47761.461273    46.086864
Apr      1985.31  2491.1800            4771    2994  38769.720704   -18.797788
May      3812.67  2204.3475            1095    1889  29512.633362   -22.649477
Jun      3422.25  2797.5200            1818    4204  39540.690952    32.783603
Jul      1961.01  1422.6025            4972    2620  34372.889467   -14.137400
Aug      2343.33  3589.3800            4025    2353  39790.349781    17.303193
Sep      3544.56  1814.1975            2731    1241  30186.801327   -23.968551
Oct      2263.14  2927.5700            1740    3831  34737.613932    14.756386
Nov      2796.12  1103.9800            3077    4735  36729.108293     4.388239
Dec      2331.99  3015.7150            4794    3620 

In [43]:
df['Growth Rate'] = df['Total Sales'].pct_change() * 100

print(df)

     Electronics   Clothing  Home & Kitchen  Sports   Total Sales  Growth Rate
Jan      4024.89  2733.9400            4390    4796  50758.330000          NaN
Feb      3437.64  3025.8300            1590    1711  32107.556957   -36.744261
Mar      2531.25  3083.6300            4711    4697  47761.461273    48.754579
Apr      1985.31  2491.1800            4771    2994  38769.720704   -18.826351
May      3812.67  2204.3475            1095    1889  29512.633362   -23.877106
Jun      3422.25  2797.5200            1818    4204  39540.690952    33.978864
Jul      1961.01  1422.6025            4972    2620  34372.889467   -13.069578
Aug      2343.33  3589.3800            4025    2353  39790.349781    15.760852
Sep      3544.56  1814.1975            2731    1241  30186.801327   -24.135371
Oct      2263.14  2927.5700            1740    3831  34737.613932    15.075505
Nov      2796.12  1103.9800            3077    4735  36729.108293     5.732962
Dec      2331.99  3015.7150            4794    3620 

## Step 5: Apply Randomized Discount

Discount is applied based on roll number:
- Even roll number → 10% discount on Electronics
- Odd roll number → 15% discount on Clothing

In [44]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    66703.160000
Feb    41835.282697
Mar    62833.095852
Apr    50992.384352
May    38489.773756
Jun    51816.439816
Jul    45335.432389
Aug    52116.820633
Sep    39493.423456
Oct    45514.399436
Nov    48446.941255
Dec    57603.737848
dtype: float64


In [45]:
df['Clothing'] = df['Clothing'] * 0.85

print(df)

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan      4024.89  2323.849000            4390    4796  50758.330000   
Feb      3437.64  2571.955500            1590    1711  32107.556957   
Mar      2531.25  2621.085500            4711    4697  47761.461273   
Apr      1985.31  2117.503000            4771    2994  38769.720704   
May      3812.67  1873.695375            1095    1889  29512.633362   
Jun      3422.25  2377.892000            1818    4204  39540.690952   
Jul      1961.01  1209.212125            4972    2620  34372.889467   
Aug      2343.33  3050.973000            4025    2353  39790.349781   
Sep      3544.56  1542.067875            2731    1241  30186.801327   
Oct      2263.14  2488.434500            1740    3831  34737.613932   
Nov      2796.12   938.383000            3077    4735  36729.108293   
Dec      2331.99  2563.357750            4794    3620  43822.719525   

     Growth Rate  
Jan          NaN  
Feb   -36.744261  
Mar    48.754579  


In [46]:
df['Electronics'] = df['Electronics'] * 0.90

print(df)

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan     3622.401  2323.849000            4390    4796  50758.330000   
Feb     3093.876  2571.955500            1590    1711  32107.556957   
Mar     2278.125  2621.085500            4711    4697  47761.461273   
Apr     1786.779  2117.503000            4771    2994  38769.720704   
May     3431.403  1873.695375            1095    1889  29512.633362   
Jun     3080.025  2377.892000            1818    4204  39540.690952   
Jul     1764.909  1209.212125            4972    2620  34372.889467   
Aug     2108.997  3050.973000            4025    2353  39790.349781   
Sep     3190.104  1542.067875            2731    1241  30186.801327   
Oct     2036.826  2488.434500            1740    3831  34737.613932   
Nov     2516.508   938.383000            3077    4735  36729.108293   
Dec     2098.791  2563.357750            4794    3620  43822.719525   

     Growth Rate  
Jan          NaN  
Feb   -36.744261  
Mar    48.754579  


# Part I: Randomized Sales Data Generation

This section generates random monthly sales data using NumPy and converts it into a Pandas DataFrame.

## Step 1: Initialize Random Seed

The roll number is used as a random seed so that each student gets unique sales data.

In [47]:
np.random.seed(902503053)

## Step 2: Generate Sales Data

Random sales data is generated for 12 months and 4 product categories:
- Electronics
- Clothing
- Home & Kitchen
- Sports

Sales values range between 1000 and 5000 units.

In [48]:
sales_data = np.random.randint(1000, 5001, size=(12,4))

print(sales_data)

[[2196 3479 4721 4809]
 [1045 1992 4039 3218]
 [3389 1915 1668 2102]
 [1343 3623 2411 2849]
 [1363 1060 2601 1379]
 [2577 1994 2410 4392]
 [4923 4292 1715 4513]
 [1992 1373 1149 2673]
 [2713 2214 4522 3366]
 [3204 1337 2539 2291]
 [3086 1026 3225 3494]
 [2867 4946 1722 1632]]


In [49]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

## Step 3: Convert NumPy Array into Pandas DataFrame

The generated sales data is converted into a Pandas DataFrame using month names as index labels and product categories as column names.