# Lab Assignment 3
## PCS221 Cloud Computing

### Q1: Sales Data Analysis

Name: Malkeet Singh   
Roll Number: 902503053

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Step 1: Initialize Random Seed

The roll number is used as the random seed to generate unique sales data.

In [20]:
np.random.seed(902503045)

In [21]:
sales_data = np.random.randint(1000, 5001, size=(12,4))

print(sales_data)

[[4969 3784 4390 4796]
 [4244 4188 1590 1711]
 [3125 4268 4711 4697]
 [2451 3448 4771 2994]
 [4707 3051 1095 1889]
 [4225 3872 1818 4204]
 [2421 1969 4972 2620]
 [2893 4968 4025 2353]
 [4376 2511 2731 1241]
 [2794 4052 1740 3831]
 [3452 1528 3077 4735]
 [2879 4174 4794 3620]]


In [22]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [23]:
df = pd.DataFrame(
    sales_data,
    columns=['Electronics', 'Clothing', 'Home & Kitchen', 'Sports'],
    index=months
)

print(df)

     Electronics  Clothing  Home & Kitchen  Sports
Jan         4969      3784            4390    4796
Feb         4244      4188            1590    1711
Mar         3125      4268            4711    4697
Apr         2451      3448            4771    2994
May         4707      3051            1095    1889
Jun         4225      3872            1818    4204
Jul         2421      1969            4972    2620
Aug         2893      4968            4025    2353
Sep         4376      2511            2731    1241
Oct         2794      4052            1740    3831
Nov         3452      1528            3077    4735
Dec         2879      4174            4794    3620


In [24]:
print(df.head())

     Electronics  Clothing  Home & Kitchen  Sports
Jan         4969      3784            4390    4796
Feb         4244      4188            1590    1711
Mar         3125      4268            4711    4697
Apr         2451      3448            4771    2994
May         4707      3051            1095    1889


In [25]:
print(df.describe())

       Electronics     Clothing  Home & Kitchen       Sports
count    12.000000    12.000000       12.000000    12.000000
mean   3544.666667  3484.416667     3309.500000  3224.250000
std     909.420528  1027.285431     1467.358883  1264.542255
min    2421.000000  1528.000000     1095.000000  1241.000000
25%    2857.750000  2916.000000     1798.500000  2237.000000
50%    3288.500000  3828.000000     3551.000000  3307.000000
75%    4277.000000  4177.500000     4726.000000  4327.250000
max    4969.000000  4968.000000     4972.000000  4796.000000


In [26]:
category_total = df.sum()

print(category_total)

Electronics       42536
Clothing          41813
Home & Kitchen    39714
Sports            38691
dtype: int64


In [27]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    17939
Feb    11733
Mar    16801
Apr    13664
May    10742
Jun    14119
Jul    11982
Aug    14239
Sep    10859
Oct    12417
Nov    12792
Dec    15467
dtype: int64


In [28]:
avg_growth = df['Growth Rate'].mean()

print(avg_growth)

NameError: name 'growth' is not defined

In [ ]:
avg_growth = growth.mean()

print(avg_growth)

In [ ]:
df['Total Sales'] = df.sum(axis=1)

print(df)

In [ ]:
df['Growth Rate'] = df['Total Sales'].pct_change() * 100

print(df)

In [ ]:
df['Electronics'] = df['Electronics'] * 0.90

In [ ]:
df['Clothing'] = df['Clothing'] * 0.85

In [ ]:
print(df)

In [ ]:
plt.figure(figsize=(10,6))

for column in ['Electronics', 'Clothing', 'Home & Kitchen', 'Sports']:
    plt.plot(df.index, df[column], marker='o', label=column)

plt.title('Monthly Sales Trends')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.legend()
plt.grid(True)

plt.show()

In [ ]:
plt.figure(figsize=(8,6))

sns.boxplot(data=df[['Electronics', 'Clothing',
                     'Home & Kitchen', 'Sports']])

plt.title('Sales Distribution')

plt.show()

# Conclusion

The sales data was generated and analyzed using NumPy and Pandas. Different statistical operations and visualizations were performed successfully using Matplotlib and Seaborn.