In [1]:
import numpy as np
import pandas as pd

# Part I: Randomized Sales Data Generation

This section generates random monthly sales data using NumPy and converts it into a Pandas DataFrame.

## Step 1: Initialize Random Seed

The roll number is used as a random seed so that each student gets unique sales data.

In [6]:
np.random.seed(902503043)

## Step 2: Generate Sales Data

Random sales data is generated for 12 months and 4 product categories:
- Electronics
- Clothing
- Home & Kitchen
- Sports

Sales values range between 1000 and 5000 units.

In [3]:
sales_data = np.random.randint(1000, 5001, size=(12,4))

print(sales_data)

[[4969 3784 4390 4796]
 [4244 4188 1590 1711]
 [3125 4268 4711 4697]
 [2451 3448 4771 2994]
 [4707 3051 1095 1889]
 [4225 3872 1818 4204]
 [2421 1969 4972 2620]
 [2893 4968 4025 2353]
 [4376 2511 2731 1241]
 [2794 4052 1740 3831]
 [3452 1528 3077 4735]
 [2879 4174 4794 3620]]


In [4]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

## Step 3: Convert NumPy Array into Pandas DataFrame

The generated sales data is converted into a Pandas DataFrame using month names as index labels and product categories as column names.

In [5]:
df = pd.DataFrame(
    sales_data,
    columns=['Electronics', 'Clothing', 'Home & Kitchen', 'Sports'],
    index=months
)

print(df)

     Electronics  Clothing  Home & Kitchen  Sports
Jan         4969      3784            4390    4796
Feb         4244      4188            1590    1711
Mar         3125      4268            4711    4697
Apr         2451      3448            4771    2994
May         4707      3051            1095    1889
Jun         4225      3872            1818    4204
Jul         2421      1969            4972    2620
Aug         2893      4968            4025    2353
Sep         4376      2511            2731    1241
Oct         2794      4052            1740    3831
Nov         3452      1528            3077    4735
Dec         2879      4174            4794    3620
