# Part III: Visualizations (Matplotlib and Seaborn)

This section visualizes sales data using line plots and box plots.

## Step 1: Monthly Sales Trends

Line plots are used to visualize monthly sales trends for different product categories.

In [70]:
plt.figure(figsize=(10,6))

for column in ['Electronics', 'Clothing', 'Home & Kitchen', 'Sports']:
    plt.plot(df.index, df[column], marker='o', label=column)

plt.title('Monthly Sales Trends')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.legend()
plt.grid(True)

plt.show()

NameError: name 'plt' is not defined

## Step 2: Box Plot for Sales Distribution

Box plots are used to analyze the distribution and spread of sales values for each category.

In [ ]:


plt.figure(figsize=(8,6))

sns.boxplot(data=df[['Electronics', 'Clothing',
                     'Home & Kitchen', 'Sports']])

plt.title('Sales Distribution')

plt.show()

# Part II: Data Manipulation and Analysis (Pandas)

This section performs statistical analysis and data manipulation using Pandas.

In [71]:
import numpy as np
import pandas as pd

## Step 1: Display First 5 Rows and Summary Statistics

The first 5 rows and statistical summary of the dataset are displayed for analysis.

In [72]:
print(df.head())

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan    3260.1609  1975.271650            4390    4796  65890.580000   
Feb    2784.4884  2186.162175            1590    1711  41037.644197   
Mar    2050.3125  2227.922675            4711    4697  62117.426352   
Apr    1608.1011  1799.877550            4771    2994  50420.176352   
May    3088.2627  1592.641069            1095    1889  37777.854631   

     Growth Rate  
Jan          NaN  
Feb   -37.718496  
Mar    51.366940  
Apr   -18.830867  
May   -25.073934  


In [73]:
print(df.describe())

       Electronics     Clothing  Home & Kitchen       Sports   Total Sales  \
count    12.000000    12.000000       12.000000    12.000000     12.000000   
mean   2325.655800  1818.887278     3309.500000  3224.250000  49433.665968   
std     596.670809   536.249415     1467.358883  1264.542255   8823.391733   
min    1588.418100   797.625550     1095.000000  1241.000000  37777.854631   
25%    1874.969775  1522.170225     1798.500000  2237.000000  43896.123501   
50%    2157.584850  1998.239925     3551.000000  3307.000000  49210.954304   
75%    2806.139700  2180.681109     4726.000000  4327.250000  52737.605875   
max    3260.160900  2593.327050     4972.000000  4796.000000  65890.580000   

       Growth Rate  
count    11.000000  
mean      2.169538  
std      27.924866  
min     -37.718496  
25%     -21.566048  
50%       7.029780  
75%      16.983284  
max      51.366940  


## Step 2: Calculate Total Sales

Total sales are calculated:
- Category-wise
- Month-wise

In [74]:
category_total = df.sum()

print(category_total)

Electronics        27907.869600
Clothing           21826.647331
Home & Kitchen     39714.000000
Sports             38691.000000
Total Sales       593203.991616
Growth Rate           23.864920
dtype: float64


In [75]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    80312.012550
Feb    49271.576276
Mar    75855.028467
Apr    61574.324135
May    45417.684466
Jun    61904.961735
Jul    55122.185316
Aug    62227.791027
Sep    46996.387895
Oct    54383.653962
Nov    58883.244785
Dec    69418.522851
dtype: float64


## Step 3: Average Sales Growth

Percentage growth between consecutive months is calculated for each category.

In [76]:
growth = df.pct_change()

print(growth)

     Electronics  Clothing  Home & Kitchen    Sports  Total Sales  Growth Rate
Jan          NaN       NaN             NaN       NaN          NaN          NaN
Feb    -0.145905  0.106765       -0.637813 -0.643244    -0.377185          NaN
Mar    -0.263666  0.019102        1.962893  1.745178     0.513669    -2.361850
Apr    -0.215680 -0.192127        0.012736 -0.362572    -0.188309    -1.366595
May     0.920441 -0.115139       -0.770488 -0.369071    -0.250739     0.331534
Jun    -0.102401  0.269092        0.660274  1.225516     0.351442    -2.401624
Jul    -0.426982 -0.491477        1.734873 -0.376784    -0.120041    -1.341567
Aug     0.194961  1.523108       -0.190467 -0.101908     0.142860    -2.190097
Sep     0.512617 -0.494565       -0.321491 -0.472588    -0.243012    -2.701047
Oct    -0.361517  0.613700       -0.362871  2.087027     0.153913    -1.633355
Nov     0.235505 -0.622902        0.768391  0.235970     0.070298    -0.543263
Dec    -0.165991  1.731675        0.558011 -0.235480

In [77]:
avg_growth = growth.mean()

print(avg_growth)

Electronics       0.016489
Clothing          0.213385
Home & Kitchen    0.310368
Sports            0.248367
Total Sales       0.021695
Growth Rate      -1.256550
dtype: float64


## Step 4: Add New Columns

Two new columns are added:
- Total Sales
- Growth Rate

In [78]:
df['Total Sales'] = df.sum(axis=1)

print(df)

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan    3260.1609  1975.271650            4390    4796  80312.012550   
Feb    2784.4884  2186.162175            1590    1711  49271.576276   
Mar    2050.3125  2227.922675            4711    4697  75855.028467   
Apr    1608.1011  1799.877550            4771    2994  61574.324135   
May    3088.2627  1592.641069            1095    1889  45417.684466   
Jun    2772.0225  2021.208200            1818    4204  61904.961735   
Jul    1588.4181  1027.830306            4972    2620  55122.185316   
Aug    1898.0973  2593.327050            4025    2353  62227.791027   
Sep    2871.0936  1310.757694            2731    1241  46996.387895   
Oct    1833.1434  2115.169325            1740    3831  54383.653962   
Nov    2264.8572   797.625550            3077    4735  58883.244785   
Dec    1888.9119  2178.854087            4794    3620  69418.522851   

     Growth Rate  
Jan          NaN  
Feb   -37.718496  
Mar    51.366940  


In [79]:
df['Growth Rate'] = df['Total Sales'].pct_change() * 100

print(df)

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan    3260.1609  1975.271650            4390    4796  80312.012550   
Feb    2784.4884  2186.162175            1590    1711  49271.576276   
Mar    2050.3125  2227.922675            4711    4697  75855.028467   
Apr    1608.1011  1799.877550            4771    2994  61574.324135   
May    3088.2627  1592.641069            1095    1889  45417.684466   
Jun    2772.0225  2021.208200            1818    4204  61904.961735   
Jul    1588.4181  1027.830306            4972    2620  55122.185316   
Aug    1898.0973  2593.327050            4025    2353  62227.791027   
Sep    2871.0936  1310.757694            2731    1241  46996.387895   
Oct    1833.1434  2115.169325            1740    3831  54383.653962   
Nov    2264.8572   797.625550            3077    4735  58883.244785   
Dec    1888.9119  2178.854087            4794    3620  69418.522851   

     Growth Rate  
Jan          NaN  
Feb   -38.649805  
Mar    53.952916  


## Step 5: Apply Randomized Discount

Discount is applied based on roll number:
- Even roll number → 10% discount on Electronics
- Odd roll number → 15% discount on Clothing

In [80]:
monthly_total = df.sum(axis=1)

print(monthly_total)

Jan    94733.445100
Feb    57504.577046
Mar    89595.216559
Apr    72728.476473
May    53056.348987
Jun    72756.493884
Jul    65319.476965
Aug    73110.106023
Sep    55125.762339
Oct    63918.685483
Nov    69766.001327
Dec    81918.180648
dtype: float64


In [81]:
df['Clothing'] = df['Clothing'] * 0.85

print(df)

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan    3260.1609  1678.980903            4390    4796  80312.012550   
Feb    2784.4884  1858.237849            1590    1711  49271.576276   
Mar    2050.3125  1893.734274            4711    4697  75855.028467   
Apr    1608.1011  1529.895917            4771    2994  61574.324135   
May    3088.2627  1353.744908            1095    1889  45417.684466   
Jun    2772.0225  1718.026970            1818    4204  61904.961735   
Jul    1588.4181   873.655760            4972    2620  55122.185316   
Aug    1898.0973  2204.327992            4025    2353  62227.791027   
Sep    2871.0936  1114.144040            2731    1241  46996.387895   
Oct    1833.1434  1797.893926            1740    3831  54383.653962   
Nov    2264.8572   677.981717            3077    4735  58883.244785   
Dec    1888.9119  1852.025974            4794    3620  69418.522851   

     Growth Rate  
Jan          NaN  
Feb   -38.649805  
Mar    53.952916  


In [82]:
df['Electronics'] = df['Electronics'] * 0.90

print(df)

     Electronics     Clothing  Home & Kitchen  Sports   Total Sales  \
Jan   2934.14481  1678.980903            4390    4796  80312.012550   
Feb   2506.03956  1858.237849            1590    1711  49271.576276   
Mar   1845.28125  1893.734274            4711    4697  75855.028467   
Apr   1447.29099  1529.895917            4771    2994  61574.324135   
May   2779.43643  1353.744908            1095    1889  45417.684466   
Jun   2494.82025  1718.026970            1818    4204  61904.961735   
Jul   1429.57629   873.655760            4972    2620  55122.185316   
Aug   1708.28757  2204.327992            4025    2353  62227.791027   
Sep   2583.98424  1114.144040            2731    1241  46996.387895   
Oct   1649.82906  1797.893926            1740    3831  54383.653962   
Nov   2038.37148   677.981717            3077    4735  58883.244785   
Dec   1700.02071  1852.025974            4794    3620  69418.522851   

     Growth Rate  
Jan          NaN  
Feb   -38.649805  
Mar    53.952916  


# Part I: Randomized Sales Data Generation

This section generates random monthly sales data using NumPy and converts it into a Pandas DataFrame.

## Step 1: Initialize Random Seed

The roll number is used as a random seed so that each student gets unique sales data.

In [83]:
np.random.seed(902503053)

## Step 2: Generate Sales Data

Random sales data is generated for 12 months and 4 product categories:
- Electronics
- Clothing
- Home & Kitchen
- Sports

Sales values range between 1000 and 5000 units.

In [84]:
sales_data = np.random.randint(1000, 5001, size=(12,4))

print(sales_data)

[[2196 3479 4721 4809]
 [1045 1992 4039 3218]
 [3389 1915 1668 2102]
 [1343 3623 2411 2849]
 [1363 1060 2601 1379]
 [2577 1994 2410 4392]
 [4923 4292 1715 4513]
 [1992 1373 1149 2673]
 [2713 2214 4522 3366]
 [3204 1337 2539 2291]
 [3086 1026 3225 3494]
 [2867 4946 1722 1632]]


In [85]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

## Step 3: Convert NumPy Array into Pandas DataFrame

The generated sales data is converted into a Pandas DataFrame using month names as index labels and product categories as column names.